/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: Gianmarco (https://sketchfab.com/GianmArt)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/lucario-32ab2458321e495084fe3bc3b3bf6a91
Title: Lucario
*/

import React from 'react'
import { useGLTF, useTexture } from '@react-three/drei'

export default function Lucario(props) {
  const { nodes, materials } = useGLTF('/scene.gltf')
  const name = useTexture('/textures/desk/cushion.png')

  return (
    <group {...props} dispose={null}>
      <group name="Sketchfab_model" rotation={[-Math.PI / 2, 0, 0]}>
        <mesh name="Object_2" geometry={nodes.Object_2.geometry} material={materials.Material} />
        <mesh
          name="Object_3"
          geometry={nodes.Object_3.geometry}
          material={materials['Material.006']}
        />
        <mesh
          name="Object_4"
          geometry={nodes.Object_4.geometry}
          material={materials['Material.005']}
        />
        <mesh
          name="Object_5"
          geometry={nodes.Object_5.geometry}
          material={materials['Material.009']}
        >
          <meshMatcapMaterial map={name} />
        </mesh>
        <mesh
          name="Object_6"
          geometry={nodes.Object_6.geometry}
          material={materials['Material.010']}
        />
        <mesh
          name="Object_7"
          geometry={nodes.Object_7.geometry}
          material={materials['Material.024']}
        />
        <mesh
          name="Object_8"
          geometry={nodes.Object_8.geometry}
          material={materials['Material.001']}
        />
        <mesh
          name="Object_9"
          geometry={nodes.Object_9.geometry}
          material={materials['Material.002']}
        />
        <mesh
          name="Object_10"
          geometry={nodes.Object_10.geometry}
          material={materials['Material.007']}
        />
        <mesh
          name="Object_11"
          geometry={nodes.Object_11.geometry}
          material={materials['Material.011']}
        />
      </group>
    </group>
  )
}

useGLTF.preload('/scene.gltf')
