/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: jackbaeten (https://sketchfab.com/jackbaeten)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/macbook-pro-m3-16-inch-2024-8e34fc2b303144f78490007d91ff57c4
Title: macbook pro M3 16 inch 2024
*/

import { useGSAP } from '@gsap/react'
import { useGLTF, useVideoTexture } from '@react-three/drei'
import gsap from 'gsap'
import { useRef } from 'react'

export default function MacBook(props) {
  const group = useRef()
  const { nodes, materials } = useGLTF('/macbook/scene.gltf')
  const txt = useVideoTexture(`/textures/project/project${props.projectNo+1}.mp4`)
  useGSAP(()=>{
    if(group.current){
      gsap.from(group.current.rotation,{
      y: Math.PI / 2,
      duration: 1,
      ease: 'power3.out',
    })
    }
  },[txt,group.current])


  return (
    <group {...props} dispose={null}>
      <group
        name="tracking_node_placeholder_69"
        rotation={[Math.PI / 2, 0, 0]}
        userData={{ name: 'tracking_node_placeholder_69' }}>
        <group name="XUSrUKqmCVOWkVt_64" userData={{ name: 'XUSrUKqmCVOWkVt_64' }}>
          <group name="BoBvWqDHZjAeVrp_44" userData={{ name: 'BoBvWqDHZjAeVrp_44' }}>
            <mesh
              name="Object_10"
              castShadow
              receiveShadow
              geometry={nodes.Object_10.geometry}
              material={materials.AibnXCKcAbewWhH}
              userData={{ name: 'Object_10' }}
            />
            <mesh
              name="Object_12"
              castShadow
              receiveShadow
              geometry={nodes.Object_12.geometry}
              material={materials.WeLyzRwUVIhQGgM}
              userData={{ name: 'Object_12' }}
            />
            <mesh
              name="Object_14"
              castShadow
              receiveShadow
              geometry={nodes.Object_14.geometry}
              material={materials.UhoCLqHkvkDmxOA}
              userData={{ name: 'Object_14' }}
            />
            <mesh
              name="Object_16"
              castShadow
              receiveShadow
              geometry={nodes.Object_16.geometry}
              material={materials.zhGRTuGrQoJflBD}
              userData={{ name: 'Object_16' }}
            />
            <mesh
              name="Object_18"
              castShadow
              receiveShadow
              geometry={nodes.Object_18.geometry}
              material={materials.zCLdUynNQOzVMqx}
              userData={{ name: 'Object_18' }}
            />
            <mesh
              name="Object_20"
              castShadow
              receiveShadow
              geometry={nodes.Object_20.geometry}
              material={materials.jwuTsnFxKtBUxpK}
              userData={{ name: 'Object_20' }}
            />
            <mesh
              name="Object_22"
              castShadow
              receiveShadow
              geometry={nodes.Object_22.geometry}
              material={materials.lmWQsEjxpsebDlK}
              userData={{ name: 'Object_22' }}
            />
            <mesh
              name="Object_24"
              castShadow
              receiveShadow
              geometry={nodes.Object_24.geometry}
              material={materials.jwuTsnFxKtBUxpK}
              userData={{ name: 'Object_24' }}
            />
            <mesh
              name="Object_26"
              castShadow
              receiveShadow
              geometry={nodes.Object_26.geometry}
              material={materials.MycfwscjQZRVSoj}
              userData={{ name: 'Object_26' }}
            />
            <mesh
              name="Object_28"
              castShadow
              receiveShadow
              geometry={nodes.Object_28.geometry}
              material={materials.bsmYIMHYRqMuLqz}
              userData={{ name: 'Object_28' }}
            />
            <mesh
              name="Object_30"
              castShadow
              receiveShadow
              geometry={nodes.Object_30.geometry}
              material={materials.LtEafgAVRolQqRw}
              userData={{ name: 'Object_30' }}
            />
            <mesh
              name="Object_32"
              castShadow
              receiveShadow
              geometry={nodes.Object_32.geometry}
              material={materials.iyDJFXmHelnMTbD}
              userData={{ name: 'Object_32' }}
            />
            <mesh
              name="Object_34"
              castShadow
              receiveShadow
              geometry={nodes.Object_34.geometry}
              material={materials.eJObPwhgFzvfaoZ}
              userData={{ name: 'Object_34' }}
            />
            <mesh
              name="Object_36"
              castShadow
              receiveShadow
              geometry={nodes.Object_36.geometry}
              material={materials.jwuTsnFxKtBUxpK}
              userData={{ name: 'Object_36' }}
            />
            <mesh
              name="Object_38"
              castShadow
              receiveShadow
              geometry={nodes.Object_38.geometry}
              material={materials.nDsMUuDKliqGFdU}
              userData={{ name: 'Object_38' }}
            />
            <mesh
              name="Object_40"
              castShadow
              receiveShadow
              geometry={nodes.Object_40.geometry}
              material={materials.LtEafgAVRolQqRw}
              userData={{ name: 'Object_40' }}
            />
            <mesh
              name="Object_42"
              castShadow
              receiveShadow
              geometry={nodes.Object_42.geometry}
              material={materials.CRQixVLpahJzhJc}
              userData={{ name: 'Object_42' }}
            />
            <mesh
              name="Object_44"
              castShadow
              receiveShadow
              geometry={nodes.Object_44.geometry}
              material={materials.IcpudUyxprDYhfw}
              userData={{ name: 'Object_44' }}
            />
            <mesh
              name="Object_46"
              castShadow
              receiveShadow
              geometry={nodes.Object_46.geometry}
              material={materials.jwuTsnFxKtBUxpK}
              userData={{ name: 'Object_46' }}
            />
            <mesh
              name="Object_48"
              castShadow
              receiveShadow
              geometry={nodes.Object_48.geometry}
              material={materials.YYwBgwvcyZVOOAA}
              userData={{ name: 'Object_48' }}
            />
            <mesh
              name="Object_50"
              castShadow
              receiveShadow
              geometry={nodes.Object_50.geometry}
              material={materials.jwuTsnFxKtBUxpK}
              userData={{ name: 'Object_50' }}
            />
            <mesh
              name="Object_52"
              castShadow
              receiveShadow
              geometry={nodes.Object_52.geometry}
              material={materials.jwuTsnFxKtBUxpK}
              userData={{ name: 'Object_52' }}
            />
            <mesh
              name="Object_54"
              castShadow
              receiveShadow
              geometry={nodes.Object_54.geometry}
              material={materials.SLGkCohDDelqXBu}
              userData={{ name: 'Object_54' }}
            />
            <mesh
              name="Object_56"
              castShadow
              receiveShadow
              geometry={nodes.Object_56.geometry}
              material={materials.WDumMKBWVQxmraD}
              userData={{ name: 'Object_56' }}
            />
            <mesh
              name="Object_58"
              castShadow
              receiveShadow
              geometry={nodes.Object_58.geometry}
              material={materials.WnHKXHhScfUbJQi}
              userData={{ name: 'Object_58' }}
            />
            <mesh
              name="Object_60"
              castShadow
              receiveShadow
              geometry={nodes.Object_60.geometry}
              material={materials.jwuTsnFxKtBUxpK}
              userData={{ name: 'Object_60' }}
            />
            <mesh
              name="Object_62"
              castShadow
              receiveShadow
              geometry={nodes.Object_62.geometry}
              material={materials.ZNhRrZtaKWQYAab}
              userData={{ name: 'Object_62' }}
            />
            <mesh
              name="Object_64"
              castShadow
              receiveShadow
              geometry={nodes.Object_64.geometry}
              material={materials.IcpudUyxprDYhfw}
              userData={{ name: 'Object_64' }}
            />
            <mesh
              name="Object_66"
              castShadow
              receiveShadow
              geometry={nodes.Object_66.geometry}
              material={materials.fNHiBfcxHUJCahl}
              userData={{ name: 'Object_66' }}
            />
            <mesh
              name="Object_68"
              castShadow
              receiveShadow
              geometry={nodes.Object_68.geometry}
              material={materials.bsEIHfblEXNcUMs}
              userData={{ name: 'Object_68' }}
            />
            <mesh
              name="Object_70"
              castShadow
              receiveShadow
              geometry={nodes.Object_70.geometry}
              material={materials.CRQixVLpahJzhJc}
              userData={{ name: 'Object_70' }}
            />
            <mesh
              name="Object_72"
              castShadow
              receiveShadow
              geometry={nodes.Object_72.geometry}
              material={materials.SABLxXNNESCdgUy}
              userData={{ name: 'Object_72' }}
            />
            <mesh
              name="Object_74"
              castShadow
              receiveShadow
              geometry={nodes.Object_74.geometry}
              material={materials.LpqXZqhaGCeSzdu}
              userData={{ name: 'Object_74' }}
            />
            <mesh
              name="Object_76"
              castShadow
              receiveShadow
              geometry={nodes.Object_76.geometry}
              material={materials.sIfSZcqgDlKMJPf}
              userData={{ name: 'Object_76' }}
            />
            <mesh
              name="Object_78"
              castShadow
              receiveShadow
              geometry={nodes.Object_78.geometry}
              material={materials.bsmYIMHYRqMuLqz}
              userData={{ name: 'Object_78' }}
            />
            <mesh
              name="Object_80"
              castShadow
              receiveShadow
              geometry={nodes.Object_80.geometry}
              material={materials.jwuTsnFxKtBUxpK}
              userData={{ name: 'Object_80' }}
            />
            <mesh
              name="Object_82"
              castShadow
              receiveShadow
              geometry={nodes.Object_82.geometry}
              material={materials.gMtYExgrEUqPfln}
              userData={{ name: 'Object_82' }}
            />
            <mesh
              name="Object_84"
              castShadow
              receiveShadow
              geometry={nodes.Object_84.geometry}
              material={materials.WnHKXHhScfUbJQi}
              userData={{ name: 'Object_84' }}
            />
            <mesh
              name="Object_86"
              castShadow
              receiveShadow
              geometry={nodes.Object_86.geometry}
              material={materials.nDsMUuDKliqGFdU}
              userData={{ name: 'Object_86' }}
            />
            <mesh
              name="Object_88"
              castShadow
              receiveShadow
              geometry={nodes.Object_88.geometry}
              material={materials.bsEIHfblEXNcUMs}
              userData={{ name: 'Object_88' }}
            />
            <mesh
              name="Object_90"
              castShadow
              receiveShadow
              geometry={nodes.Object_90.geometry}
              material={materials.uInNDOueKeBTGQB}
              userData={{ name: 'Object_90' }}
            />
            <mesh
              name="Object_92"
              castShadow
              receiveShadow
              geometry={nodes.Object_92.geometry}
              material={materials.hmEmmncwVomyUTC}
              userData={{ name: 'Object_92' }}
            />
            <mesh
              name="Object_94"
              castShadow
              receiveShadow
              geometry={nodes.Object_94.geometry}
              material={materials.WeLyzRwUVIhQGgM}
              userData={{ name: 'Object_94' }}
            />
            <mesh
              name="Object_96"
              castShadow
              receiveShadow
              geometry={nodes.Object_96.geometry}
              material={materials.KclpPzxoRwZAoer}
              userData={{ name: 'Object_96' }}
            />
          </group>
          <group name="VCQqxpxkUlzqcJI_62" userData={{ name: 'VCQqxpxkUlzqcJI_62' }}>
            <mesh
              name="Object_99"
              castShadow
              receiveShadow
              geometry={nodes.Object_99.geometry}
              material={materials.wjAYtisbflXilXi}
              userData={{ name: 'Object_99' }}
            />
            <mesh
              name="Object_101"
              castShadow
              receiveShadow
              geometry={nodes.Object_101.geometry}
              material={materials.zobIbiekuagXEVU}
              userData={{ name: 'Object_101' }}
            />
            <mesh
              name="Object_103"
              castShadow
              receiveShadow
              geometry={nodes.Object_103.geometry}
              material={materials.RyKTMHTpkkwQkvB}
              userData={{ name: 'Object_103' }}
            />
            <mesh
              name="Object_105"
              castShadow
              receiveShadow
              geometry={nodes.Object_105.geometry}
              material={materials.jwuTsnFxKtBUxpK}
              userData={{ name: 'Object_105' }}
            />
            <mesh
              name="Object_107"
              castShadow
              receiveShadow
              geometry={nodes.Object_107.geometry}
              material={materials.JvMFZolVCdpPqjj}
              userData={{ name: 'Object_107' }}
            />
            <mesh
              name="Object_109"
              castShadow
              receiveShadow
              geometry={nodes.Object_109.geometry}
              material={materials.UBYmHfGRfHbOXyc}
              userData={{ name: 'Object_109' }}
            />
            <mesh
              name="Object_111"
              castShadow
              receiveShadow
              geometry={nodes.Object_111.geometry}
              material={materials.uInNDOueKeBTGQB}
              userData={{ name: 'Object_111' }}
            />
            <mesh
              name="Object_113"
              castShadow
              receiveShadow
              geometry={nodes.Object_113.geometry}
              material={materials.gOXiFODBFKnUyyU}
              userData={{ name: 'Object_113' }}
            />
            <mesh
              name="Object_115"
              castShadow
              receiveShadow
              geometry={nodes.Object_115.geometry}
              material={materials.eBwkWuOBScacrgP}
              userData={{ name: 'Object_115' }}
            />
            <mesh
              name="Object_117"
              castShadow
              receiveShadow
              geometry={nodes.Object_117.geometry}
              material={materials.jwuTsnFxKtBUxpK}
              userData={{ name: 'Object_117' }}
            />
            <mesh
              name="Object_119"
              castShadow
              receiveShadow
              geometry={nodes.Object_119.geometry}
              material={materials.jwuTsnFxKtBUxpK}
              userData={{ name: 'Object_119' }}
            />
            <mesh
              name="Object_121"
              castShadow
              receiveShadow
              geometry={nodes.Object_121.geometry}
              material={materials.nDsMUuDKliqGFdU}
              userData={{ name: 'Object_121' }}
            />
            <mesh
              name="Object_123"
              castShadow
              receiveShadow
              geometry={nodes.Object_123.geometry}
              material={materials.sfCQkHOWyrsLmor}
              userData={{ name: 'Object_123' }}
            >
              <meshBasicMaterial map={txt}/>
            </mesh>
            <mesh
              name="Object_125"
              castShadow
              receiveShadow
              geometry={nodes.Object_125.geometry}
              material={materials.CdgEAaPUlrQWQuD}
              userData={{ name: 'Object_125' }}
            />
            <mesh
              name="Object_127"
              castShadow
              receiveShadow
              geometry={nodes.Object_127.geometry}
              material={materials.ZCDwChwkbBfITSW}
              userData={{ name: 'Object_127' }}
            />
            <mesh
              name="Object_129"
              castShadow
              receiveShadow
              geometry={nodes.Object_129.geometry}
              material={materials.XCYkeTCxqFmKTKe}
              userData={{ name: 'Object_129' }}
            />
            <mesh
              name="Object_131"
              castShadow
              receiveShadow
              geometry={nodes.Object_131.geometry}
              material={materials.MycfwscjQZRVSoj}
              userData={{ name: 'Object_131' }}
            />
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/macbook/scene.gltf')
